# This is a basic workflow to help you get started with Actions

name: Tester

on:
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: show github event
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"

      - name: show contains token
        env:
          HAS_TOKEN: ${{ contains(github.event.body, 'token')
        run: |
          echo Has token
          echo ${HAS_TOKEN}
