# This is a basic workflow to help you get started with Actions

name: Tester

on:
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: show github event
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"

      - name: show body
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: echo "$BODY"
        
      - name: show contains token
        env:
          HAS_TOKEN: ${{ contains(github.event.pull_request.body, '[ch-new]') }}
        run: |
          echo Has token
          echo "$HAS_TOKEN"
          
      - name: show has label
        env:
          HAS_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'new clubhouse story') }}
        run: echo "$HAS_LABEL"
        
      - name: if token or label
        if: contains(github.event.pull_request.body, '[ch-new]') || contains(github.event.pull_request.labels.*.name, 'new clubhouse story')
        run: echo It has either a token or label
